// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppModuleScssNamespace {
    export interface IAppModuleScss {
        stylesHeader: string;
        stylesImage: string;
    }
}

declare const AppModuleScssModule: AppModuleScssNamespace.IAppModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: AppModuleScssNamespace.IAppModuleScss;
};

export = AppModuleScssModule;
