// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppModuleLessNamespace {
    export interface IAppModuleLess {
        file: string;
        mappings: string;
        names: string;
        sources: string;
        sourcesContent: string;
        stylesContainer: string;
        version: string;
    }
}

declare const AppModuleLessModule: AppModuleLessNamespace.IAppModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: AppModuleLessNamespace.IAppModuleLess;
};

export = AppModuleLessModule;
