// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppModuleLessNamespace {
    export interface IAppModuleLess {
        stylesContainer: string;
    }
}

declare const AppModuleLessModule: AppModuleLessNamespace.IAppModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: AppModuleLessNamespace.IAppModuleLess;
};

export = AppModuleLessModule;
